version: 2
jobs:
  build:
    docker:
      - image: node:8

    working_directory: ~/repo

    environment:
      - STAGING_BRANCH: develop
      - PRODUCTION_BRANCH: master

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Create built data files
          command: npm run data

      - run:
          name: Test
          command: npm run test

      - run:
          name: Build production site
          command: |
            if [ "${CIRCLE_BRANCH}" == "${PRODUCTION_BRANCH}" ]; then
              npm run build
            else
              echo "Skip building production site"
            fi

      - add_ssh_keys:
          fingerprints:
            - "6c:0c:07:ae:bc:6e:4d:f0:80:33:84:a5:eb:ab:13:6d"

      - deploy:
          name: Deploy production to gh-pages
          command: |
            if [ "${CIRCLE_BRANCH}" == "${PRODUCTION_BRANCH}" ]; then
              cd dist
               git init
               git config user.name "Deborah Gordon"
               git config user.email "deborah_gordon1@brown.edu"
               git add .
               git commit -m "CI deploy [skip ci]"
               git remote add origin git@github.com:dxgordon/OCIPlus.git
               git push origin --force --quiet master
               rm -rf .git
            else
              echo "Not the branch you're looking for, skipping deploy"
            fi
