_prefs: 
  mapid: carnegiecomms.1d1c0ebe
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -45.7031
  - 43.5804
  - 2
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 18
minzoom: 0
name: OCI 2014
source: "mapbox:///carnegiecomms.7025qo1b"
styles: 
  - style.mss
template: ''
